name: Generate index.html

on:
  push:
    branches: [main]

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate index.html
        run: |
          echo "<html><body><h1>File List</h1><ul>" > index.html
          find . -type f ! -path "./.git/*" ! -path "./.github/*" | sed 's|^\./||' | while read file; do
            echo "<li><a href=\"$file\">$file</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html

      - name: Commit and push index.html
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Auto-generate index.html" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
