name: Generate index.html

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Generate smart index.html
        run: |
          echo "<html><head><style>
            body { font-family: sans-serif; }
            h2 { margin-top: 2em; }
            table { border-collapse: collapse; width: 100%; }
            th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
            th { background-color: #f4f4f4; }
          </style></head><body><h1>Document Index</h1>" > index.html

          find . -type f \( -name '*.pdf' -o -name '*.html' -o -name '*.md' -o -name '*.txt' -o -name '*.docx' \) | sort | while read file; do
            dir=$(dirname "$file")
            fname=$(basename "$file")
            size=$(du -h "$file" | cut -f1)
            mod=$(date -r "$file" "+%Y-%m-%d %H:%M")
            ext="${fname##*.}"

            # Start a new section for each folder
            if [[ "$dir" != "$last_dir" ]]; then
              echo "<h2>$dir</h2><table><tr><th>File</th><th>Type</th><th>Size</th><th>Last Modified</th></tr>" >> index.html
              last_dir="$dir"
            fi

            echo "<tr><td><a href='${file#./}'>$fname</a></td><td>$ext</td><td>$size</td><td>$mod</td></tr>" >> index.html
          done

          echo "</table></body></html>" >> index.html

      - name: Commit and push index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
