---
name: Generate index.html

"on":
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate index.html
        run: |
          cat << 'EOF' > index.html
          <!DOCTYPE html>
          <html><head><title>Document Index</title></head><body>
          <h1>Available Documents</h1>
          <p>Generated: $(date)</p>
          <ul>
          EOF

          find ./docs -name "*.pdf" -o -name "*.html" -o -name "*.md" \
            -o -name "*.txt" -o -name "*.docx" | \
            sed 's|^\./||' | \
            sort | \
            while read file; do
              echo "<li><a href=\"$file\">$file</a></li>"
            done >> index.html

          echo "</ul></body></html>" >> index.html

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet index.html; then
            git add index.html
            git commit -m "Auto-update index.html"
            git push
          fi
